name: Automatizar Publicação no Instagram

on:
  workflow_dispatch:  # Permite acionar manualmente o workflow
  push:
    branches:
      - main  # Aciona o workflow quando houver um push na branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer checkout do código
      - name: Checkout do código
        uses: actions/checkout@v3

      # Passo 2: Configurar Python
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Passo 3: Instalar dependências
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Passo 4: Baixar e Configurar Chrome
      - name: Baixar e Configurar Chrome
        run: |
          wget https://storage.googleapis.com/chrome-for-testing-public/133.0.6943.98/linux64/chrome-linux64.zip
          unzip chrome-linux64.zip
          sudo mv chrome-linux64/chrome /usr/local/bin/chrome
          sudo chmod +x /usr/local/bin/chrome

      # Passo 5: Baixar e Configurar ChromeDriver
      - name: Baixar e Configurar ChromeDriver
        run: |
          CHROMEDRIVER_VERSION=133.0.6943.98  # Versão compatível com o Chrome
          wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      # Passo 6: Executar o script
      - name: Executar script de automação
        env:
          INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
          INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
        run: |
          export INSTAGRAM_USERNAME=$INSTAGRAM_USERNAME
          export INSTAGRAM_PASSWORD=$INSTAGRAM_PASSWORD
          python app.py
